//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMastery.Lab02CLR.TracedConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMastery.Lab02CLR.TracedConsoleApp.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following output formats are allowed:.
        /// </summary>
        internal static string AllowedFormattsBegin {
            get {
                return ResourceManager.GetString("AllowedFormattsBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly couldn&apos;t be loaded: .
        /// </summary>
        internal static string AssemblyLoadException {
            get {
                return ResourceManager.GetString("AssemblyLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory hasn&apos;t been found.
        /// </summary>
        internal static string DirectoryException {
            get {
                return ResourceManager.GetString("DirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path file for plugins doesn&apos;t located in app.config.
        /// </summary>
        internal static string FileForPluginsNotFoundException {
            get {
                return ResourceManager.GetString("FileForPluginsNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, push any botton....
        /// </summary>
        internal static string FinishedAppNote {
            get {
                return ResourceManager.GetString("FinishedAppNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option --f | -format is required.
        /// </summary>
        internal static string FormatConstraint {
            get {
                return ResourceManager.GetString("FormatConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t present in allowed formats\n.
        /// </summary>
        internal static string FormatDoesntExistExeption {
            get {
                return ResourceManager.GetString("FormatDoesntExistExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format used for represent programm result..
        /// </summary>
        internal static string FormatHelp {
            get {
                return ResourceManager.GetString("FormatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --f | -format &lt;format&gt;.
        /// </summary>
        internal static string FormatOptions {
            get {
                return ResourceManager.GetString("FormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets help for options.
        /// </summary>
        internal static string HelpHelp {
            get {
                return ResourceManager.GetString("HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --h | -help.
        /// </summary>
        internal static string HelpOptions {
            get {
                return ResourceManager.GetString("HelpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter options.
        /// </summary>
        internal static string InputNote {
            get {
                return ResourceManager.GetString("InputNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Assamblies dont&apos;t exist on  which  .
        /// </summary>
        internal static string OtherAssemblyFilesNotFoundException {
            get {
                return ResourceManager.GetString("OtherAssemblyFilesNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path for output file doesn&apos;t exists.
        /// </summary>
        internal static string OutputFileException {
            get {
                return ResourceManager.GetString("OutputFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file for saving program result..
        /// </summary>
        internal static string OutputHelp {
            get {
                return ResourceManager.GetString("OutputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --o | -output &lt;output&gt;.
        /// </summary>
        internal static string OutputOptions {
            get {
                return ResourceManager.GetString("OutputOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfile for directory is too long.
        /// </summary>
        internal static string PathTooLong {
            get {
                return ResourceManager.GetString("PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin type hasn&apos;t been added.
        /// </summary>
        internal static string PluginTypeAddException {
            get {
                return ResourceManager.GetString("PluginTypeAddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of getting types from the plugins assemblies.
        /// </summary>
        internal static string ReflectionTypesException {
            get {
                return ResourceManager.GetString("ReflectionTypesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was successfully writen in the file.
        /// </summary>
        internal static string SuccessWriting {
            get {
                return ResourceManager.GetString("SuccessWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to .
        /// </summary>
        internal static string UnathorizedException {
            get {
                return ResourceManager.GetString("UnathorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error undefined.
        /// </summary>
        internal static string UndefinedExceptionMethod {
            get {
                return ResourceManager.GetString("UndefinedExceptionMethod", resourceCulture);
            }
        }
    }
}
